function obj = readScene(file_name)
    %Label index
    PILLOW1 = 1;
    PILLOW2 = PILLOW1+1;
    PILLOW3 = PILLOW2+1;
    PILLOW4 = PILLOW3+1;
    MATTRESS = PILLOW4+1;
    BLANKET = MATTRESS+1;
    BEDFRAME = BLANKET+1;
    MAT = BEDFRAME+1;
    TABLE_R = MAT+1;
    TABLE_L = TABLE_R+1;
    SOFA = TABLE_L+1;
    FLOOR = SOFA+1;
    BACK_WALL = FLOOR+1;
    LEFT_WALL = BACK_WALL+1;
    RIGHT_WALL = LEFT_WALL+1;
    FRONT_WALL = RIGHT_WALL+1;
    COFFEE_TABLE = FRONT_WALL+1;
    VASE = COFFEE_TABLE+1;
    DESK = VASE+1;
    CHAIR = DESK+1;
    CUPBOARD = CHAIR+1;
    NUM_LABELS = CUPBOARD; 
    %Lengths in m
    global ROOM_LENGTH = 5;
    global ROOM_WIDTH = 5;
    PILLOW_LENGTH = 0.5;
    PILLOW_WIDTH = 1;
    BED_LENGTH = 2;
    BED_WIDTH = 1.5;
    BLANKET_LENGTH = 1.5;
    CTABLE_LENGTH = 0.8;
    CTABLE_WIDTH = 0.8;
    VASE_WIDTH = 0.3;
    VASE_LENGTH = 0.3;
    DESK_WIDTH = 0.5;
    DESK_LENGTH = 1.5;
    CHAIR_LENGTH = 0.5;
    CHAIR_WIDTH = 0.5;
    CUPBOARD_LENGTH = 2;
    CUPBOARD_WIDTH = 0.5;
    %Region index
    BACK = 1;
    LEFT = 2;
    RIGHT = 3;
    FRONT = 4;
    CENTER = 5;
    %Element index
    global COL_H = 1;
    global COL_S = 2;
    global COL_V = 3;
    global COORD_X = 4; %Lower left corner
    global COORD_Y = 5; %Lower left corner
    global WIDTH = 6;
    global LENGTH = 7;
    global REGION = 8;
    global PAIR = 9;
    global NUM_ELEMENTS = 9;

    obj = zeros(NUM_LABELS, NUM_ELEMENTS);

    obj(PILLOW1,:) = [rand, 0.8, 0.5, 0.5*ROOM_WIDTH-0.5*PILLOW_WIDTH, ROOM_LENGTH-1.3*PILLOW_LENGTH, PILLOW_WIDTH, PILLOW_LENGTH, CENTER, BEDFRAME];
    obj(MATTRESS,:) = [rand, 0.8, 0.5, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BED_LENGTH, CENTER, BEDFRAME];
    obj(BLANKET,:) = [rand, 0.8, 0.5, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BLANKET_LENGTH, CENTER, BEDFRAME];
    obj(BEDFRAME,:) = [rand, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BED_LENGTH, BACK, BEDFRAME];
    obj(COFFEE_TABLE,:) = [rand, rand, rand, 0.5*ROOM_WIDTH-0.5*CTABLE_WIDTH, 0.3*ROOM_LENGTH-0.5*CTABLE_LENGTH, CTABLE_WIDTH, CTABLE_LENGTH, CENTER, NA];
    obj(VASE,:) = [rand, rand, rand, 0.5*ROOM_WIDTH+0.5*BED_WIDTH + 0.1, ROOM_LENGTH-VASE_LENGTH, VASE_WIDTH, VASE_LENGTH, BACK, BEDFRAME];
    obj(DESK,:) = [rand, rand, rand, ROOM_WIDTH-DESK_WIDTH, 1, DESK_WIDTH, DESK_LENGTH, RIGHT, CHAIR];
    obj(CHAIR,:) = [rand, rand, rand, ROOM_WIDTH-CHAIR_WIDTH-CHAIR_WIDTH, 1+0.5*(DESK_LENGTH-CHAIR_LENGTH), CHAIR_WIDTH, CHAIR_LENGTH, RIGHT, DESK];
    obj(CUPBOARD,:) = [rand, rand, rand, 0, ROOM_LENGTH-CUPBOARD_LENGTH, CUPBOARD_WIDTH, CUPBOARD_LENGTH, LEFT, NA];
    obj(FLOOR,:)= [rand, rand, rand, 0, 0, ROOM_WIDTH, ROOM_LENGTH, CENTER, NA];
    obj(BACK_WALL,:) = [rand, rand, rand, 0, ROOM_LENGTH, ROOM_WIDTH, 0.05, BACK, NA];
    obj(LEFT_WALL,:) = [rand, rand, rand, 0, 0, 0.05, ROOM_LENGTH, LEFT, NA];
    obj(RIGHT_WALL,:) = [rand, rand, rand, ROOM_WIDTH, 0, 0.05, ROOM_LENGTH, RIGHT, NA];
    obj(FRONT_WALL,:) = [rand, rand, rand, 0, 0, ROOM_WIDTH, 0.05, FRONT, NA];
%{
    obj(PILLOW1,:) = [215/360, rand, rand, 0.5*ROOM_WIDTH-0.5*PILLOW_WIDTH, ROOM_LENGTH-1.3*PILLOW_LENGTH, PILLOW_WIDTH, PILLOW_LENGTH, CENTER, BEDFRAME];
    obj(MATTRESS,:) = [0, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BED_LENGTH, CENTER, BEDFRAME];
    obj(BLANKET,:) = [186/360, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BLANKET_LENGTH, CENTER, BEDFRAME];
    obj(BEDFRAME,:) = [0, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BED_LENGTH, BACK, BEDFRAME];
    obj(COFFEE_TABLE,:) = [138/360, rand, rand, 0.5*ROOM_WIDTH-0.5*CTABLE_WIDTH, 0.3*ROOM_LENGTH-0.5*CTABLE_LENGTH, CTABLE_WIDTH, CTABLE_LENGTH, CENTER, NA];
    obj(VASE,:) = [0, rand, rand, 0.5*ROOM_WIDTH+0.5*BED_WIDTH + 0.1, ROOM_LENGTH-VASE_LENGTH, VASE_WIDTH, VASE_LENGTH, BACK, BEDFRAME];
    obj(DESK,:) = [99/360, rand, rand, ROOM_WIDTH-DESK_WIDTH, 1, DESK_WIDTH, DESK_LENGTH, RIGHT, CHAIR];
    obj(CHAIR,:) = [99/360, rand, rand, ROOM_WIDTH-CHAIR_WIDTH-CHAIR_WIDTH, 1+0.5*(DESK_LENGTH-CHAIR_LENGTH), CHAIR_WIDTH, CHAIR_LENGTH, RIGHT, DESK];
    obj(CUPBOARD,:) = [0, rand, rand, 0, ROOM_LENGTH-CUPBOARD_LENGTH, CUPBOARD_WIDTH, CUPBOARD_LENGTH, LEFT, NA];
    obj(FLOOR,:)= [166/360, rand, rand, 0, 0, ROOM_WIDTH, ROOM_LENGTH, CENTER, NA];
    obj(BACK_WALL,:) = [183/360, rand, rand, 0, ROOM_LENGTH, ROOM_WIDTH, 0.05, BACK, NA];
    obj(LEFT_WALL,:) = [0, rand, rand, 0, 0, 0.05, ROOM_LENGTH, LEFT, NA];
    obj(RIGHT_WALL,:) = [0, rand, rand, ROOM_WIDTH, 0, 0.05, ROOM_LENGTH, RIGHT, NA];
    obj(FRONT_WALL,:) = [0, rand, rand, 0, 0, ROOM_WIDTH, 0.05, FRONT, NA];
%}
%{
    obj(PILLOW1,:) = [170/360, rand, rand, 0.5*ROOM_WIDTH-0.5*PILLOW_WIDTH, ROOM_LENGTH-1.3*PILLOW_LENGTH, PILLOW_WIDTH, PILLOW_LENGTH, CENTER, BEDFRAME];
    obj(MATTRESS,:) = [170/360, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BED_LENGTH, CENTER, BEDFRAME];
    obj(BLANKET,:) = [170/360, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BLANKET_LENGTH, CENTER, BEDFRAME];
    obj(BEDFRAME,:) = [170/360, rand, rand, 0.5*ROOM_WIDTH-0.5*BED_WIDTH, ROOM_LENGTH-BED_LENGTH, BED_WIDTH, BED_LENGTH, BACK, BEDFRAME];
    obj(COFFEE_TABLE,:) = [170/360, rand, rand, 0.5*ROOM_WIDTH-0.5*CTABLE_WIDTH, 0.3*ROOM_LENGTH-0.5*CTABLE_LENGTH, CTABLE_WIDTH, CTABLE_LENGTH, CENTER, NA];
    obj(VASE,:) = [170/360, rand, rand, 0.5*ROOM_WIDTH+0.5*BED_WIDTH + 0.1, ROOM_LENGTH-VASE_LENGTH, VASE_WIDTH, VASE_LENGTH, BACK, BEDFRAME];
    obj(DESK,:) = [340/360, rand, rand, ROOM_WIDTH-DESK_WIDTH, 1, DESK_WIDTH, DESK_LENGTH, RIGHT, CHAIR];
    obj(CHAIR,:) = [340/360, rand, rand, ROOM_WIDTH-CHAIR_WIDTH-CHAIR_WIDTH, 1+0.5*(DESK_LENGTH-CHAIR_LENGTH), CHAIR_WIDTH, CHAIR_LENGTH, RIGHT, DESK];
    obj(CUPBOARD,:) = [170/360, rand, rand, 0, ROOM_LENGTH-CUPBOARD_LENGTH, CUPBOARD_WIDTH, CUPBOARD_LENGTH, LEFT, NA];
    obj(FLOOR,:)= [170/360, rand, rand, 0, 0, ROOM_WIDTH, ROOM_LENGTH, CENTER, NA];
    obj(BACK_WALL,:) = [170/360, rand, rand, 0, ROOM_LENGTH, ROOM_WIDTH, 0.05, BACK, NA];
    obj(LEFT_WALL,:) = [170/360, rand, rand, 0, 0, 0.05, ROOM_LENGTH, LEFT, NA];
    obj(RIGHT_WALL,:) = [340/360, rand, rand, ROOM_WIDTH, 0, 0.05, ROOM_LENGTH, RIGHT, NA];
    obj(FRONT_WALL,:) = [170/360, rand, rand, 0, 0, ROOM_WIDTH, 0.05, FRONT, NA];
%}


    %Draw layout
    order = [FLOOR, COFFEE_TABLE, DESK, CHAIR, VASE, CUPBOARD, BEDFRAME, MATTRESS, BLANKET, PILLOW1, BACK_WALL, LEFT_WALL, RIGHT_WALL, FRONT_WALL];
    figure
    drawScene(obj, order);
endfunction
